name: Rust

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Code linting
        run: cargo clippy --workspace --features "rtlsdr,airspy,hackrf,ssh" --all-targets -- -D warnings

      - name: Code formatting
        run: cargo fmt --all --check

      - name: Build
        run: cargo build --verbose --features "rtlsdr,airspy,hackrf,ssh"

      - name: Run tests
        run: cargo test --workspace --features "rtlsdr,airspy,hackrf,ssh"

      - name: Check docs
        env:
          RUSTDOCFLAGS: "-D rustdoc::all -A rustdoc::private-doc-tests"
        run: cargo doc --features "rtlsdr,airspy,hackrf,ssh" --no-deps
